#pragma once

// Cool! We can also identify the hierarchy via. indentation

#define PRIORITY_ENTRY_TASK 1

#define PRIORITY_NAMESERVER 1

/**
 * Detectors
 */
#define PRIORITY_SENSOR_DETECTOR 1
#define PRIORITY_DELAY_DETECTOR 1

/**
 * Detectives
 */

#define PRIORITY_SENSOR_TIMEOUT_DETECTIVE 1

/**
 * Servers
 */
#define PRIORITY_CLOCK_SERVER 2
  #define PRIORITY_CLOCK_NOTIFIER 1

#define PRIORITY_UART1_TX_SERVER 2
  #define PRIORITY_UART1_TX_NOTIFIER 1

#define PRIORITY_UART1_RX_SERVER 2
  #define PRIORITY_UART1_RX_NOTIFIER 1

#define PRIORITY_UART2_TX_SERVER 6
  #define PRIORITY_UART2_TX_NOTIFIER 5

#define PRIORITY_UART2_RX_SERVER 6
  #define PRIORITY_UART2_RX_NOTIFIER 5

#define PRIORITY_TRAIN_CONTROLLER_SERVER 4
  #define PRIORITY_TRAIN_CONTROLLER_TASK 3

#define PRIORITY_LOGGING_WAREHOUSE 6
  #define PRIORITY_LOGGING_COURIER 30

#define PRIORITY_IDLE_TASK 31

#define PRIORITY_INTERACTIVE 10
  #define PRIORITY_INTERACTIVE_DIAGNOSTICS 12
